Feature/#4/multilingual
innovolve-ai/template-electron-vuex-vuetify pull request #30
Opened 2022-02-24 13:43 UTC by Rahul139-stack

Added multilingual feature and please review it

2022-03-02 06:02 UTC, wildone approved these changes

2022-03-02 06:05 UTC, wildone requested changes
can we please do this PR into Develop branch.

2022-03-02 12:44 UTC, Rahul139-stack commented
> can we please do this PR into Develop branch.
Base  branch changed to develop

2022-03-02 12:50 UTC, Rahul139-stack commented on cypress.json
> +  "baseUrl": "http://localhost:3000"
#32 ticket raised for the same

2022-03-02 12:53 UTC, Rahul139-stack commented
Reopen PR

2022-03-03 05:26 UTC, ankitvats1 approved these changes

2022-03-03 05:33 UTC, wildone approved these changes

2022-03-03 05:33 UTC, merged